# Default values for xmitd-cloud.

simulator:
    image: xmidt/rdkb-simulator


#######################################################
#################### Child Charts #####################
#######################################################

caduceus:
  caduceus:
    image: xmidt/caduceus:0.10

scytale:
  scytale:
    image: xmidt/scytale:0.13
    fanout:
      endpoints: ["http://petasos:6400/api/v2/device/send"]

petasos:
  petasos:
    image: xmidt/petasos:latest

talaria:
  talaria:
    image: xmidt/talaria:latest

tr1d1um:
  tr1d1um:
    image: xmidt/tr1d1um:latest
